# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <get_conversion_factor>
  "cf",
  # <get_conversion_factor>
  "date_end",
  # <get_conversion_factor>
  "date_start",
  # <download_link_table>
  "File Name",
  # <download_link_table>
  "Name",
  NULL
))
