# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <get_conversion_factor>
  "conversion_factor",
  # <get_conversion_factor>
  "date_effective",
  # <download_link_table>
  "File Name",
  # <download_link_table>
  "Name",
  NULL
))
